app:
  version: ^project.version^
  name: ^project.name^

server:
  port: ${API_PORT}
  error:
    whitelabel:
      enabled: false
    include-stacktrace: never
    include-message: always
spring:
  application:
    name: meu-guia-api
  profiles:
    active: prod
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    property-naming-strategy: SNAKE_CASE