spring:
  datasource:
    url: jdbc:postgresql://localhost:54321/db-test
    username: test
    password: test
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: false
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
logging:
  level:
    br.ufpb.dcx.apps4society.meuguiapbapi: DEBUG
