server:
  port: 8080

spring:
  application:
    name: meu-guia-api
  profiles:
    active: prod
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION}
  jackson:
    property-naming-strategy: SNAKE_CASE