-- Insert data in city table
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500106', 'Água Branca','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500205', 'Aguiar','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500304', 'Alagoa Grande','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500403', 'Alagoa Nova','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500502', 'Alagoinha','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500536', 'Alcantil','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500577', 'Algodão de Jandaíra','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500601', 'Alhandra','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500700', 'São João do Rio do Peixe','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500734', 'Amparo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500775', 'Aparecida','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500809', 'Araçagi','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2500908', 'Arara','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501005', 'Araruna','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501104', 'Areia','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501153', 'Areia de Baraúnas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501203', 'Areial','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501302', 'Aroeiras','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501351', 'Assunção','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501401', 'Baía da Traição','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501500', 'Bananeiras','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501534', 'Baraúna','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501575', 'Barra de Santana','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501609', 'Barra de Santa Rosa','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501708', 'Barra de São Miguel','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501807', 'Bayeux','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2501906', 'Belém','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502003', 'Belém do Brejo do Cruz','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502052', 'Bernardino Batista','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502102', 'Boa Ventura','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502151', 'Boa Vista','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502201', 'Bom Jesus','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502300', 'Bom Sucesso','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502409', 'Bonito de Santa Fé','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502508', 'Boqueirão','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502607', 'Igaracy','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502706', 'Borborema','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502805', 'Brejo do Cruz','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2502904', 'Brejo dos Santos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503001', 'Caaporã','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503100', 'Cabaceiras','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503209', 'Cabedelo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503308', 'Cachoeira dos Índios','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503407', 'Cacimba de Areia','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503506', 'Cacimba de Dentro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503555', 'Cacimbas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503605', 'Caiçara','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503704', 'Cajazeiras','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503753', 'Cajazeirinhas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503803', 'Caldas Brandão','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2503902', 'Camalaú','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504009', 'Campina Grande','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504033', 'Capim','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504074', 'Caraúbas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504108', 'Carrapateira','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504157', 'Casserengue','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504207', 'Catingueira','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504306', 'Catolé do Rocha','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504355', 'Caturité','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504405', 'Conceição','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504504', 'Condado','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504603', 'Conde','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504702', 'Congo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504801', 'Coremas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504850', 'Coxixola','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2504900', 'Cruz do Espírito Santo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505006', 'Cubati','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505105', 'Cuité','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505204', 'Cuitegi','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505238', 'Cuité de Mamanguape','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505279', 'Curral de Cima','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505303', 'Curral Velho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505352', 'Damião','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505402', 'Desterro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505501', 'Vista Serrana','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505600', 'Diamante','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505709', 'Dona Inês','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505808', 'Duas Estradas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2505907', 'Emas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506004', 'Esperança','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506103', 'Fagundes','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506202', 'Frei Martinho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506251', 'Gado Bravo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506301', 'Guarabira','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506400', 'Gurinhém','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506509', 'Gurjão','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506608', 'Ibiara','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506707', 'Imaculada','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506806', 'Ingá','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2506905', 'Itabaiana','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507002', 'Itaporanga','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507101', 'Itapororoca','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507200', 'Itatuba','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507309', 'Jacaraú','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507408', 'Jericó','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507507', 'João Pessoa','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507606', 'Juarez Távora','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507705', 'Juazeirinho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507804', 'Junco do Seridó','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2507903', 'Juripiranga','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508000', 'Juru','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508109', 'Lagoa','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508208', 'Lagoa de Dentro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508307', 'Lagoa Seca','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508406', 'Lastro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508505', 'Livramento','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508554', 'Logradouro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508604', 'Lucena','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508703', 'Mãe d''Água','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508802', 'Malta','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2508901', 'Mamanguape','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509008', 'Manaíra','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509057', 'Marcação','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509107', 'Mari','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509156', 'Marizópolis','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509206', 'Massaranduba','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509305', 'Mataraca','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509339', 'Matinhas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509370', 'Mato Grosso','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509396', 'Maturéia','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509404', 'Mogeiro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509503', 'Montadas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509602', 'Monte Horebe','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509701', 'Monteiro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509800', 'Mulungu','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2509909', 'Natuba','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510006', 'Nazarezinho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510105', 'Nova Floresta','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510204', 'Nova Olinda','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510303', 'Nova Palmeira','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510402', 'Olho d''Água','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510501', 'Olivedos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510600', 'Ouro Velho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510659', 'Parari','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510709', 'Passagem','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510808', 'Patos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2510907', 'Paulista','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511004', 'Pedra Branca','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511103', 'Pedra Lavrada','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511202', 'Pedras de Fogo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511301', 'Piancó','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511400', 'Picuí','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511509', 'Pilar','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511608', 'Pilões','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511707', 'Pilõezinhos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511806', 'Pirpirituba','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2511905', 'Pitimbu','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512002', 'Pocinhos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512036', 'Poço Dantas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512077', 'Poço de José de Moura','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512101', 'Pombal','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512200', 'Prata','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512309', 'Princesa Isabel','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512408', 'Puxinanã','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512507', 'Queimadas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512606', 'Quixaba','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512705', 'Remígio','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512721', 'Pedro Régis','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512747', 'Riachão','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512754', 'Riachão do Bacamarte','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512762', 'Riachão do Poço','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512788', 'Riacho de Santo Antônio','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512804', 'Riacho dos Cavalos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2512903', 'Rio Tinto','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513000', 'Salgadinho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513109', 'Salgado de São Félix','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513158', 'Santa Cecília','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513208', 'Santa Cruz','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513307', 'Santa Helena','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513356', 'Santa Inês','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513406', 'Santa Luzia','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513505', 'Santana de Mangueira','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513604', 'Santana dos Garrotes','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513653', 'Joca Claudino','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513703', 'Santa Rita','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513802', 'Santa Teresinha','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513851', 'Santo André','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513901', 'São Bento','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513927', 'São Bentinho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513943', 'São Domingos do Cariri','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513968', 'São Domingos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2513984', 'São Francisco','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514008', 'São João do Cariri','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514107', 'São João do Tigre','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514206', 'São José da Lagoa Tapada','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514305', 'São José de Caiana','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514404', 'São José de Espinharas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514453', 'São José dos Ramos','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514503', 'São José de Piranhas','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514552', 'São José de Princesa','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514602', 'São José do Bonfim','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514651', 'São José do Brejo do Cruz','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514701', 'São José do Sabugi','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514800', 'São José dos Cordeiros','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2514909', 'São Mamede','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515005', 'São Miguel de Taipu','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515104', 'São Sebastião de Lagoa de Roça','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515203', 'São Sebastião do Umbuzeiro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515302', 'Sapé','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515401', 'São Vicente do Seridó','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515500', 'Serra Branca','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515609', 'Serra da Raiz','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515708', 'Serra Grande','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515807', 'Serra Redonda','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515906', 'Serraria','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515930', 'Sertãozinho','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2515971', 'Sobrado','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516003', 'Solânea','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516102', 'Soledade','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516151', 'Sossêgo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516201', 'Sousa','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516300', 'Sumé','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516409', 'Tacima','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516508', 'Taperoá','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516607', 'Tavares','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516706', 'Teixeira','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516755', 'Tenório','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516805', 'Triunfo','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2516904', 'Uiraúna','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2517001', 'Umbuzeiro','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2517100', 'Várzea','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2517209', 'Vieirópolis','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;
INSERT INTO city(id, name, state, state_abbreviation, country, created_at) VALUES ('2517407', 'Zabelê','Paraíba','PB','Brasil',NOW()) ON CONFLICT DO NOTHING;

