CREATE SEQUENCE IF NOT EXISTS city_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE _user
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 2) NOT NULL,
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    email      VARCHAR(255),
    password   VARCHAR(255),
    CONSTRAINT pk__user PRIMARY KEY (id)
);

CREATE TABLE attraction
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    description VARCHAR(100000)                         NOT NULL,
    map_link    VARCHAR(200)                            NOT NULL,
    city_id     BIGINT                                  NOT NULL,
    image_link  VARCHAR(500)                            NOT NULL,
    type_id     BIGINT                                  NOT NULL,
    CONSTRAINT pk_attraction PRIMARY KEY (id)
);

CREATE TABLE attraction_tourism_segmentation
(
    attraction_id           BIGINT NOT NULL,
    tourism_segmentation_id BIGINT NOT NULL
);

CREATE TABLE attraction_type
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    description VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_attraction_type PRIMARY KEY (id)
);

CREATE TABLE city
(
    id                 BIGINT       NOT NULL,
    ibge_id            BIGINT,
    name               VARCHAR(255),
    state              VARCHAR(255) NOT NULL,
    state_abbreviation VARCHAR(255) NOT NULL,
    country            VARCHAR(255) NOT NULL,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    created_by         BIGINT,
    last_modified_by   BIGINT,
    CONSTRAINT pk_city PRIMARY KEY (id)
);

CREATE TABLE more_info_link
(
    link          VARCHAR(200) NOT NULL,
    description   VARCHAR(200) NOT NULL,
    attraction_id BIGINT
);

CREATE TABLE tourism_segmentation
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(200)                            NOT NULL,
    description VARCHAR(200)                            NOT NULL,
    CONSTRAINT pk_tourism_segmentation PRIMARY KEY (id)
);

ALTER TABLE _user
    ADD CONSTRAINT uc__user_email UNIQUE (email);

ALTER TABLE city
    ADD CONSTRAINT uc_city_ibge UNIQUE (ibge_id);

ALTER TABLE attraction
    ADD CONSTRAINT FK_ATTRACTION_ON_CITY FOREIGN KEY (city_id) REFERENCES city (id);

ALTER TABLE attraction
    ADD CONSTRAINT FK_ATTRACTION_ON_TYPE FOREIGN KEY (type_id) REFERENCES attraction_type (id);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_CREATED_BY FOREIGN KEY (created_by) REFERENCES _user (id);

ALTER TABLE city
    ADD CONSTRAINT FK_CITY_ON_LAST_MODIFIED_BY FOREIGN KEY (last_modified_by) REFERENCES _user (id);

ALTER TABLE more_info_link
    ADD CONSTRAINT FK_MORE_INFO_LINK_ON_ATTRACTION FOREIGN KEY (attraction_id) REFERENCES attraction (id);

ALTER TABLE attraction_tourism_segmentation
    ADD CONSTRAINT fk_atttouseg_on_attraction FOREIGN KEY (attraction_id) REFERENCES attraction (id);

ALTER TABLE attraction_tourism_segmentation
    ADD CONSTRAINT fk_atttouseg_on_tourism_segmentation FOREIGN KEY (tourism_segmentation_id) REFERENCES tourism_segmentation (id);