name: deployment-to-prod

on:
  workflow_run:
    workflows:
      - build-and-test
    branches:
      - main
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'

      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: build docker image
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/meuguiapbapi:prod .

      - name: push docker image
        run: docker push ${{secrets.DOCKER_USERNAME}}/meuguiapbapi:prod