name: Build and Test Spring Boot application

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Project and Test
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses: actions/checkout@v4

     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         distribution: 'correto'
         java-version: '21'

     - name: Build with Maven
       run: mvn package -DskipTests

     - name: Run Tests
       run: mvn test
