name: build-and-test

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build Project and Test
    runs-on: ubuntu-latest
    environment: development

    env:
          API_PORT: ${{ vars.API_PORT }}
          DB_HOST: ${{ vars.DB_HOST }}
          DB_PORT: ${{ vars.DB_PORT }}
          DB_NAME: ${{ vars.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRATION: ${{ vars.JWT_EXPIRATION }}
          TEST_SERVER_HOST: ${{ vars.TEST_SERVER_HOST }}
          TEST_SERVER_PORT: ${{ vars.TEST_SERVER_PORT }}
          TEST_SERVER_BASE_PATH: ${{ vars.TEST_SERVER_BASE_PATH }}
          TEST_PROFILE: ${{ vars.TEST_PROFILE }}
          
    steps:
     - name: Checkout code
       uses: actions/checkout@v4
     - name: Set up JDK 21
       uses: actions/setup-java@v4
       with:
         distribution: 'corretto'
         java-version: '21'
         cache: maven
     - run: mvn --batch-mode --update-snapshots verify
     - run: mkdir staging && cp target/*.jar staging/
     - uses: actions/upload-artifact@v4
       with:
         name: Package
         path: staging